ProductManager/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ninject;
using ProductManager.Entities;

namespace ProductManager.Controllers
{
    [Authorize]
    public class FileController : _ApplicationController
    {
        private const string TempPath = @"\\fred\pmfiles";

        [Inject]
        public IRepository<FilePM, ProductManagerDatabaseContext> fileRepo { get; set; }

        // GET: File
        public ActionResult Index(string partNumber)
        {
            var files = fileRepo.GetGroup(x => x.BasePartNumber == partNumber).AsEnumerable();
            return PartialView(files);
        }

        [HttpPost]
        public ActionResult UploadFiles(HttpPostedFileBase file, string basePart)
        {
            System.IO.FileInfo fileInf = new System.IO.FileInfo(Path.Combine(TempPath, basePart.Replace("/", "~"), Uri.UnescapeDataString(file.FileName)));
            fileInf.Directory.Create();
            System.IO.File.WriteAllBytes(fileInf.FullName, ReadData(file.InputStream));

            try
            {
                fileRepo.Create(new FilePM()
                {
                    BasePartNumber = basePart,
                    Path = fileInf.FullName
                });

                return RedirectToAction("Index", new { partNumber = basePart });
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public ActionResult Download(string id)
        {
            var file = fileRepo.Get(Guid.Parse(id));

            try
            {
                string fileName = Path.Combine(TempPath, file.Path);
                return File(fileName, MimeMapping.GetMimeMapping(fileName), file.Path);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public ActionResult Delete(string id)
        {
            var file = fileRepo.Get(Guid.Parse(id));
            System.IO.FileInfo fileInf = new System.IO.FileInfo(Path.Combine(TempPath, file.Path));

            try
            {
                fileRepo.Delete(file);
                fileInf.Delete();

                return RedirectToAction("Index", new { partNumber = file.BasePartNumber });
            }
            catch (Exception)
            {

                throw;
            }
        }

        private byte[] ReadData(Stream stream)
        {
            byte[] buffer = new byte[16 * 1024];

            using (MemoryStream ms = new MemoryStream())
            {
                int read;
                while ((read = stream.Read(buffer, 0, buffer.Length)) > 0)
                {
                    ms.Write(buffer, 0, read);
                }

                return ms.ToArray();
            }
        }
    }
}

ProductManager/Views/File/Index.cshtml
@model IEnumerable<ProductManager.Entities.FilePM>

<div id="dropZone">Drop your Files here</div>

<style type="text/css">
    #dropZone {
        background: gray;
        border: black dashed 3px;
        width: 200px;
        padding: 50px;
        text-align: center;
        color: white;
    }
</style>

<table class="table cell-hovered border bordered striped">
    <tr>
        <th>
            File Name
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @switch (Path.GetExtension(item.Path))
                {
                    default:
                        <span class="fa fa-file-o"></span>
                        break;
                    case ".jpg":
                    case ".png":
                        <span class="fa fa-file-image-o"></span>
                        break;
                    case ".pdf":
                        <span class="fa fa-file-pdf-o"></span>
                        break;
                    case ".xls":
                    case ".xlsx":
                        <span class="fa fa-file-excel-o"></span>
                        break;
                    case ".doc":
                    case ".docx":
                        <span class="fa fa-file-word-o"></span>
                        break;
                    case ".txt":
                        <span class="fa fa-file-text-o"></span>
                        break;
                }
                @HttpUtility.HtmlDecode(Path.GetFileName(item.Path))
            </td>
            <td>
                @using (Html.BeginForm("Download", "File", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("id", item.ID)
                    <button type="submit" class="button fa fa-download place-right"></button>
                }
                <button type="button" class="button fa fa-remove place-right" onclick="removeFile('@item.ID')"></button>
            </td>
        </tr>
    }

</table>